### ISSUE TITLE
Addd questions related to your skills 

### ISSUE THREAD

**Issue by GabsPalomo** [trashbirdecology/ecologyInterviewPrep#1]
I was thinking that some of the questions I've gotten in job interviews are related to what skills do I have that can contribute to either the company, job, etc. It's hard for most people to talk about what skills they have so I always find that practicing this beforehand always helped.

**Comment by GabsPalomo** [comment]
Also perhaps a section for the questions the applicant could/should ask to the potential employer/PI/researcher. Something like How will authorship is handled in your lab, or am I expected to work during weekends, or similar things. I'm just throwing some ideas your way.

**Comment by trashbirdecology** [comment]
Please feel free to submit a pull request which incorporates some of the questions you have in mind

**Comment by trashbirdecology** [comment]
I added some of these types of Qs, thanks.
